# Pizza API

## To use these HTTP  endpoint install the REST Client plugin in VSCode.

GET https://pizza-api.projectcodex.net/api/pizzas

### Create a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=grac-e


### Get a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/mKgQ5AmEts/get

### Add a pizza to the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
content-type: application/json

{
    "cart_code" : "mKgQ5AmEts",
    "pizza_id" : 3
}

### Add a pizza to the cart

POST https://pizza-api.pizza-api.projectcodex.net/api/pizza-cart/add
content-type: application/json

{
    "cart_code" : "mKgQ5AmEts",
    "pizza_id" : 3
}

### Remove a pizza from the cart

POST https://pizza-api.pizza-api.projectcodex.net/api/pizza-cart/remove
content-type: application/json

{
    "cart_code" : "mKgQ5AmEts",
    "pizza_id" : 3
}

### GET all the carts for a given user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/grac-e

### GET all the active carts for a user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/grac-e/active


### Pay for a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/pay
content-type: application/json

{
    "cart_code" : "mKgQ5AmEts",
    "amount" : 400
}